### ISSUE TITLE
Classical Control rewrite support should be refactored

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#534]
https://github.com/microsoft/qsharp-runtime/blob/main/src/Simulation/QSharpFoundation/ClassicalControl.qs defines the Q# operations used in our classically controlled rewrite step (see https://github.com/microsoft/qsharp-compiler/blob/main/src/QsCompiler/Transformations/ClassicallyControlled.cs). As mentioned in a comment on the qs file, the namespace name is out of date and should be updated, along with other clean-up and refactoring to allow it to be used correctly by the rewrite step <s>without needing to be exposed publicly</s>. This refactor will need to take several steps:

- [x] Minimize number of intrinsics in ClassicalControl.qs to reduce load on implementers (#529)
- [x] Update generated code for concrete intrinsics that use interfaces to not be gate specific. (#538)
- [x] Rename namespace, updating qsharp-compiler rewrite step with new name. (#692, https://github.com/microsoft/qsharp-compiler/pull/1037)
- [x] <s>Switch Q# foundation to use interfaces for intrinsic implementation.</s> not required for rename.
- [x] <s>Change remaining callables in ClassicalControl.qs to be internal.</s> control callables will not be internal.
- [x] <s>Change all non-intrinsic callables in ClassicalControl.qs to be internal. (#535)</s> control callables will not be internal.
